resource "altinitycloud_env_certificate" "this" {
  env_name = "acme-staging"
}

locals {
  aws_account_id = "123456789012"
  region         = "us-east-1"
  zones          = ["us-east-1a", "us-east-1b"]

  // S3 buckets outside the environment that ClickHouse should be able to read
  // (e.g. a data lake or an external S3 disk, possibly living in another AWS account).
  // Defined once and referenced in BOTH blocks below so the two lists never drift apart.
  external_buckets = ["acme-data-lake", "acme-clickhouse-s3-disk"]
}

provider "aws" {
  region = local.region
}

module "altinitycloud_connect_aws" {
  source  = "altinity/connect-aws/altinitycloud"
  version = "~> 0.3" // external_buckets support in the permissions boundary requires >= 0.1.12

  pem = altinitycloud_env_certificate.this.pem

  // This will setup permissions boundary policy and resource prefix on cloud-connect module
  enable_permissions_boundary = true

  // 🔑 Required when enable_permissions_boundary = true. The permissions boundary
  //    is a hard ceiling on the IAM roles created for the environment: if a bucket
  //    is not listed here, the ClickHouse role is blocked from it (AccessDenied on
  //    s3:ListBucket) even when the bucket policy on the other account already
  //    grants access.
  external_buckets = local.external_buckets
}

resource "altinitycloud_env_aws" "this" {
  name           = altinitycloud_env_certificate.this.env_name
  aws_account_id = local.aws_account_id
  region         = local.region
  zones          = local.zones
  cidr           = "10.67.0.0/21"
  load_balancers = {
    public = {
      enabled          = true
      source_ip_ranges = ["0.0.0.0/0"]
    }
  }
  node_groups = [
    {
      node_type         = "t4g.large"
      capacity_per_zone = 10
      zones             = local.zones
      reservations      = ["SYSTEM", "ZOOKEEPER"]
    },
    {
      node_type         = "m6i.large"
      capacity_per_zone = 10
      zones             = local.zones
      reservations      = ["CLICKHOUSE"]
    }
  ]
  cloud_connect = true

  // 🔑 Registers the buckets with the Altinity control plane so the environment
  //    recognizes them. Must reference the SAME buckets passed to the
  //    altinitycloud_connect_aws module above — both sides are required.
  external_buckets = [for bucket in local.external_buckets : { name = bucket }]

  depends_on = [
    // "depends_on" is here to enforce "this resource, then altinitycloud_connect_aws" order on destroy.
    module.altinitycloud_connect_aws
  ]

  // 🚨 These are generated by the altinitycloud_connect_aws module and should not be modified.
  // Both are immutable fields, changing them will require destroy and re-creation of the environment.
  permissions_boundary_policy_arn = module.altinitycloud_connect_aws.permissions_boundary_policy_arn
  resource_prefix                 = module.altinitycloud_connect_aws.resource_prefix
}

// ⚠️ Environment provisioning is asynchronous.
// Without this data source, Terraform cannot detect provisioning failures.
// This data source waits until the environment is fully reconciled and reports errors.
data "altinitycloud_env_aws_status" "this" {
  name                           = altinitycloud_env_aws.this.name
  wait_for_applied_spec_revision = altinitycloud_env_aws.this.spec_revision
}
