query GetAWSEnvHosted($name: String!) {
  awsEnvHosted(name: $name) {
    name
    spec {
      ...AWSEnvHostedSpecFragment
    }
    specRevision
  }
}

query GetAWSEnvHostedStatus($name: String!) {
  awsEnvHosted(name: $name) {
    name
    specRevision
    status {
      appliedSpecRevision
      pendingDelete
      loadBalancers {
        internal {
          endpointServiceName
        }
      }
      errors {
        code
        message
      }
    }
  }
}

mutation CreateAWSEnvHosted($input: CreateAWSEnvHostedInput!) {
  createAWSEnvHosted(input: $input) {
    mutationId
    spec {
      ...AWSEnvHostedSpecFragment
    }
    specRevision
  }
}

mutation UpdateAWSEnvHosted($input: UpdateAWSEnvHostedInput!) {
  updateAWSEnvHosted(input: $input) {
    mutationId
    spec {
      ...AWSEnvHostedSpecFragment
    }
    specRevision
  }
}

mutation DeleteAWSEnvHosted($input: DeleteAWSEnvHostedInput!) {
  deleteAWSEnvHosted(input: $input) {
    mutationId
    pendingMFA
  }
}

fragment AWSEnvHostedSpecFragment on AWSEnvHostedSpec {
  region
  cidr
  zoneIDs
  resourcePrefix
  kmsKeyARN
  customDomains
  loadBalancers {
    public {
      enabled
      sourceIPRanges
    }
    internal {
      enabled
      sourceIPRanges
      endpointServiceAllowedPrincipals
      endpointServiceSupportedRegions
    }
  }
  nodeGroups {
    name
    nodeType
    zoneIDs
    capacityPerZone
    reservations
  }
  maintenanceWindows {
    name
    enabled
    hour
    lengthInHours
    days
  }
  endpoints {
    serviceName
    alias
  }
  externalBuckets {
    name
    kmsKeyARN
  }
  backups {
    customBucket {
      name
      region
      roleARN
    }
  }
  iceberg {
    catalogs {
      name
      type
      customS3Bucket
      customS3BucketPath
      customS3TableBucketARN
      region
      anonymousAccessEnabled
      maintenance {
        enabled
      }
      watches {
        table
        pathsRelativeToTableLocation
      }
    }
  }
  metricsEndpoint {
    enabled
    sourceIPRanges
  }
  datadog {
    enabled
    domain
    logsEnabled
    metricsEnabled
  }
}
